setup: &setup
  adapter: postgresql
  encoding: unicode
  pool: 5
  password:
  username: postgres

development:
  <<: *setup
  database: mail_sandbox_web_development
  username: mail_sandbox_web_development

staging:
  <<: *setup
  database: mail_sandbox_web_staging
  username: mail_sandbox_web_staging

test:
  <<: *setup
  database: mail_sandbox_web_test
  username: mail_sandbox_web_test

production:
  <<: *setup
  database: mail_sandbox_web_production
  username: mail_sandbox_web_production
