setup: &setup
  adapter: postgresql
  encoding: unicode
  pool: 5
  password:
  username: postgres

development:
  <<: *setup
  database: mail_sandbox_web_development

staging:
  <<: *setup
  pool: 10
  database: mail_sandbox
  username: mail_sandbox_staging

test:
  <<: *setup
  database: mail_sandbox_web_test

production:
  <<: *setup
  database: mail_sandbox_production
  username: mail_sandbox_production
