staging:
  facebook:
    app_id: ''
    app_secret: ''
  github:
    app_id: ''
    app_secret: ''
  airbrake:
    api_key: ''
    host: ''
development:
  facebook:
    app_id: ''
    app_secret: ''
  github:
    app_id: ''
    app_secret: ''
  airbrake:
    api_key: ''
    host: ''
production:
  facebook:
    app_id: ''
    app_secret: ''
  github:
    app_id: ''
    app_secret: ''
  airbrake:
    api_key: ''
    host: ''

